experiment_name: flowers102_resnet18_genmix_aug1
seed: 42
device: cuda

data:
  dataset_name: flowers102
  train_dataset_type: mixed_aug

  root: data/flowers102
  download: true

  aug_root: augmented_flowers102_train_aug1
  aug_index_path: augmented_flowers102_train_aug1/dataset_index.json

  num_aug_per_image: 1
  alpha: 1.0

  num_classes: 102
  batch_size: 32
  num_workers: 4

model:
  name: resnet18
  pretrained: true

training:
  num_epochs: 50
  optimizer: sgd
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0001

  scheduler:
    type: step_lr
    step_size: 20
    gamma: 0.1

logging:
  log_dir: logs
  log_batch_loss: false

  comet:
    project_name: OF102-augmentation-comparison
    workspace: null
    api_key_env: COMET_API_KEY
    disabled: true
