# configs/resnet18_dtd_mixed_aug_alpha05.yaml

experiment_name: resnet18_dtd_mixed_aug_alpha05
seed: 42
device: cuda

data:
  dataset_name: dtd
  train_dataset_type: mixed_aug

  # Нужен для val/test split.
  root: data/dtd
  download: true
  partition: 1

  # Offline-аугментированный train split.
  aug_root: augmented_train_dtd
  aug_index_path: augmented_train_dtd/dataset_index.json

  alpha: 0.5
  num_aug_per_image: 1

  num_classes: 47
  batch_size: 32
  num_workers: 4

model:
  name: resnet18
  pretrained: true

training:
  num_epochs: 50
  optimizer: sgd
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0001

  scheduler:
    type: step_lr
    step_size: 20
    gamma: 0.1

logging:
  log_dir: logs
  log_batch_loss: false

  comet:
    project_name: DTD-augmentation-comparison
    workspace: null
    api_key_env: COMET_API_KEY
    disabled: false
