experiment_name: miniimagenet_resnet18
seed: 42
device: cuda

data:
  dataset_name: miniimagenet
  train_dataset_type: original

  root: data/miniimagenet
  download: true

  # Сюда нужно поставить прямую ссылку на архив.
  # Архив должен после распаковки давать train/val/test.
  url: "https://doi.org/10.6084/m9.figshare.26340226"
  archive_name: miniimagenet.zip
  remove_archive: false

  num_classes: 100
  batch_size: 32
  num_workers: 4

model:
  name: resnet18
  pretrained: true

training:
  num_epochs: 50
  optimizer: sgd
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0001

  scheduler:
    type: step_lr
    step_size: 20
    gamma: 0.1

logging:
  log_dir: logs
  log_batch_loss: false

  comet:
    project_name: miniImageNet-augmentation-comparison
    workspace: null
    api_key: null
    disabled: false
